# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1089, 681)
        Main.setWindowOpacity(1.0)
        Main.setStyleSheet("")
        Main.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/imgs/img/background.png) stretch, stretch;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.verticalFrame.setStyleSheet("background-color: rgb(44, 62, 76);\n"
"\n"
"")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalFrame)
        self.label.setMaximumSize(QtCore.QSize(52, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.home = QtWidgets.QPushButton(self.verticalFrame)
        self.home.setMinimumSize(QtCore.QSize(0, 50))
        self.home.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icons/icon/home.svg);\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"left: 0%;\n"
"right: 0%;\n"
"top: 0%;\n"
"bottom: 0%;\n"
"\n"
"/* 2c3e4c */\n"
"\n"
"background: #2C3E4C;\n"
"/* f1f1f1 */\n"
"\n"
"border: 1px solid #F1F1F1;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"box-sizing: border-box;\n"
"position: absolute;\n"
"left: 0%;\n"
"right: 0%;\n"
"top: 0%;\n"
"bottom: 54.55%;\n"
"background: #55595D;\n"
"/* f1f1f1 */\n"
"border: 1px solid #F1F1F1;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icon/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon)
        self.home.setObjectName("home")
        self.verticalLayout.addWidget(self.home)
        self.clock = QtWidgets.QPushButton(self.verticalFrame)
        self.clock.setMinimumSize(QtCore.QSize(0, 50))
        self.clock.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icons/icon/home.svg);\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"left: 0%;\n"
"right: 0%;\n"
"top: 0%;\n"
"bottom: 0%;\n"
"\n"
"/* 2c3e4c */\n"
"\n"
"background: #2C3E4C;\n"
"/* f1f1f1 */\n"
"\n"
"border: 1px solid #F1F1F1;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"box-sizing: border-box;\n"
"position: absolute;\n"
"left: 0%;\n"
"right: 0%;\n"
"top: 0%;\n"
"bottom: 54.55%;\n"
"background: #55595D;\n"
"/* f1f1f1 */\n"
"border: 1px solid #F1F1F1;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.clock.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/icon/clock.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clock.setIcon(icon1)
        self.clock.setObjectName("clock")
        self.verticalLayout.addWidget(self.clock)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_35 = QtWidgets.QLabel(self.verticalFrame)
        self.label_35.setMaximumSize(QtCore.QSize(40, 40))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("res/icon/sun.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.verticalLayout.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.verticalFrame)
        self.label_36.setMaximumSize(QtCore.QSize(40, 40))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("res/icon/ring.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.verticalLayout.addWidget(self.label_36)
        self.label_34 = QtWidgets.QLabel(self.verticalFrame)
        self.label_34.setMaximumSize(QtCore.QSize(40, 40))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("res/icon/account.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout.addWidget(self.label_34)
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalFrame_2.setStyleSheet("background-color: rgb(3, 14, 22);")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.Btlich = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.Btlich.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Btlich.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/icon/Calender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btlich.setIcon(icon2)
        self.Btlich.setIconSize(QtCore.QSize(18, 18))
        self.Btlich.setObjectName("Btlich")
        self.horizontalLayout_15.addWidget(self.Btlich)
        self.dateEdit = QtWidgets.QDateEdit(self.horizontalFrame_2)
        self.dateEdit.setStyleSheet("\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"width: 119.7px;\n"
"height: 25.31px;\n"
"left: 314.41px;\n"
"top: 15.42px;\n"
"\n"
"border: 1px solid rgba(255, 255, 255, 0.5);\n"
"border-radius: 3px;\n"
"\n"
"width: 68px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 1;\n"
"flex-grow: 0;")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_15.addWidget(self.dateEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.Cld = QtWidgets.QCalendarWidget(self.horizontalFrame_2)
        self.Cld.setMaximumSize(QtCore.QSize(16777215, 500))
        self.Cld.setStyleSheet("#Cld QWidget{\n"
"color:white;\n"
"font-size:18px;\n"
"\n"
"alternate-background-color:rgb(128,128,128)\n"
"\n"
"}\n"
"#Cld QToolButton {\n"
"height: 15px;\n"
"icon-size:20px, 20px;\n"
"}")
        self.Cld.setObjectName("Cld")
        self.verticalLayout_8.addWidget(self.Cld)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Btlich_1 = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.Btlich_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Btlich_1.setText("")
        self.Btlich_1.setIcon(icon2)
        self.Btlich_1.setIconSize(QtCore.QSize(18, 18))
        self.Btlich_1.setObjectName("Btlich_1")
        self.horizontalLayout_16.addWidget(self.Btlich_1)
        self.dateEdit_1 = QtWidgets.QDateEdit(self.horizontalFrame_2)
        self.dateEdit_1.setStyleSheet("\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"width: 119.7px;\n"
"height: 25.31px;\n"
"left: 314.41px;\n"
"top: 15.42px;\n"
"\n"
"border: 1px solid rgba(255, 255, 255, 0.5);\n"
"border-radius: 3px;\n"
"\n"
"width: 68px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 1;\n"
"flex-grow: 0;")
        self.dateEdit_1.setObjectName("dateEdit_1")
        self.horizontalLayout_16.addWidget(self.dateEdit_1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.Cld_1 = QtWidgets.QCalendarWidget(self.horizontalFrame_2)
        self.Cld_1.setMaximumSize(QtCore.QSize(16777215, 500))
        self.Cld_1.setStyleSheet("#Cld_1 QWidget{\n"
"color:white;\n"
"font-size:18px;\n"
"alternate-background-color:rgb(128,128,128)\n"
"\n"
"}\n"
"#Cld_1 QToolButton {\n"
"height: 15px;\n"
"icon-size:20px, 20px;\n"
"}")
        self.Cld_1.setObjectName("Cld_1")
        self.verticalLayout_9.addWidget(self.Cld_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.bxCam = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.bxCam.setMaximumSize(QtCore.QSize(119, 16777215))
        self.bxCam.setStyleSheet("font-family: \'Inte\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"box-sizing: border-box;\n"
"\n"
"position: absolute;\n"
"width: 119.7px;\n"
"height: 16px;\n"
"left: 314.41px;\n"
"top: 15.42px;\n"
"\n"
"border: 1px solid rgba(255, 255, 255, 0.5);\n"
"border-radius: 3px;")
        self.bxCam.setEditable(False)
        self.bxCam.setObjectName("bxCam")
        self.horizontalLayout_3.addWidget(self.bxCam)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.horizontalFrame_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 1066))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Layouttime = QtWidgets.QFrame(self.widget)
        self.Layouttime.setStyleSheet("#Layouttime{\n"
"background: rgba(85, 89, 93, 0.5);\n"
"border-right: 1px solid #000000;\n"
"}\n"
"")
        self.Layouttime.setObjectName("Layouttime")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Layouttime)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table = QtWidgets.QWidget(self.Layouttime)
        self.table.setStyleSheet("")
        self.table.setObjectName("table")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.table)
        self.horizontalLayout_18.setContentsMargins(5, 0, 5, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tableWidget = QtWidgets.QTableWidget(self.table)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"font: 24pt \"Interl\";\n"
"color: rgb(255, 255, 255);\n"
"box-sizing: border-box;\n"
"width: 972.71px;\n"
"height: 60px;\n"
"left: 67.01px;\n"
"top: 115.31px;\n"
"box-sizing: border-box;\n"
"background: transparent;\n"
"borde-all: none;\n"
"border-radius: 5px;\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_18.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.table)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Layouttime)
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"box-sizing: border-box;\n"
"width: 972.71px;\n"
"height: 60px;\n"
"left: 67.01px;\n"
"top: 115.31px;\n"
"box-sizing: border-box;\n"
"background: transparent;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.Layouttime)
        self.a = QtWidgets.QFrame(self.widget)
        self.a.setMaximumSize(QtCore.QSize(678, 16777215))
        self.a.setStyleSheet("#a{\n"
"background: rgba(85, 89, 93, 0.5);\n"
"}")
        self.a.setObjectName("a")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.a)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbCam = QtWidgets.QLabel(self.a)
        self.lbCam.setMaximumSize(QtCore.QSize(680, 428))
        self.lbCam.setStyleSheet("#lbCam{\n"
"border-radius: 0.5px;\n"
"}")
        self.lbCam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbCam.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbCam.setLineWidth(0)
        self.lbCam.setText("")
        self.lbCam.setScaledContents(True)
        self.lbCam.setObjectName("lbCam")
        self.verticalLayout_6.addWidget(self.lbCam)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(9, 12))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("res/icon/left.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.StartButton = QtWidgets.QPushButton(self.a)
        self.StartButton.setMaximumSize(QtCore.QSize(9, 12))
        self.StartButton.setStyleSheet("QPushButton{\n"
"box-sizing: border-box;\n"
"background:transparent;\n"
"position: absolute;\n"
"width: 678.1px;\n"
"height: 1065.92px;\n"
"left: 1049.9px;\n"
"top: 51.08px;\n"
"\n"
"\n"
"background-color: transparent;\n"
"border-left: 1px solid #000000;\n"
"}")
        self.StartButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartButton.setIcon(icon3)
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_8.addWidget(self.StartButton)
        self.n = QtWidgets.QLabel(self.a)
        self.n.setMaximumSize(QtCore.QSize(9, 12))
        self.n.setText("")
        self.n.setPixmap(QtGui.QPixmap("res/icon/right.png"))
        self.n.setScaledContents(True)
        self.n.setObjectName("n")
        self.horizontalLayout_8.addWidget(self.n)
        self.line_2 = QtWidgets.QFrame(self.a)
        self.line_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.label_23 = QtWidgets.QLabel(self.a)
        self.label_23.setMaximumSize(QtCore.QSize(26, 12))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("res/icon/time.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.a)
        self.label_22.setMaximumSize(QtCore.QSize(18, 14))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("res/icon/sound.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.label_21 = QtWidgets.QLabel(self.a)
        self.label_21.setMaximumSize(QtCore.QSize(14, 14))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("res/icon/zoom.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.label_24 = QtWidgets.QLabel(self.a)
        self.label_24.setMaximumSize(QtCore.QSize(15, 15))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("res/icon/down.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_25 = QtWidgets.QLabel(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setStyleSheet("width: 114px;\n"
"height: 17px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.a)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("res/icon/line.png"))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_38 = QtWidgets.QLabel(self.a)
        self.label_38.setStyleSheet("width: 61px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: rgba(255, 255, 255, 0.5);\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_12.addWidget(self.label_38)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_37 = QtWidgets.QLabel(self.a)
        self.label_37.setStyleSheet("width: 127px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 1;\n"
"flex-grow: 0;")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_12.addWidget(self.label_37)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_41 = QtWidgets.QLabel(self.a)
        self.label_41.setStyleSheet("width: 112px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: rgba(255, 255, 255, 0.5);\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_13.addWidget(self.label_41)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_39 = QtWidgets.QLabel(self.a)
        self.label_39.setStyleSheet("width: 116px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 1;\n"
"flex-grow: 0;")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_13.addWidget(self.label_39)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_42 = QtWidgets.QLabel(self.a)
        self.label_42.setStyleSheet("width: 90px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: rgba(255, 255, 255, 0.5);\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_14.addWidget(self.label_42)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.label_40 = QtWidgets.QLabel(self.a)
        self.label_40.setStyleSheet("width: 121px;\n"
"height: 16px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 13px;\n"
"line-height: 16px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 1;\n"
"flex-grow: 0;")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_14.addWidget(self.label_40)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.label_28 = QtWidgets.QLabel(self.a)
        self.label_28.setStyleSheet("width: 114px;\n"
"height: 17px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 14px;\n"
"line-height: 17px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_6.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.a)
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("res/icon/line.png"))
        self.label_29.setObjectName("label_29")
        self.verticalLayout_6.addWidget(self.label_29)
        self.label_32 = QtWidgets.QLabel(self.a)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.a)
        self.label_31.setStyleSheet("position: absolute;\n"
"width: 88px;\n"
"height: 15px;\n"
"left: 1065.04px;\n"
"top: 830.45px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.label_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.comboBox_3 = QtWidgets.QComboBox(self.a)
        self.comboBox_3.setMaximumSize(QtCore.QSize(217, 16777215))
        self.comboBox_3.setStyleSheet("background: rgba(85, 89, 93, 0.5);\n"
"position: absolute;\n"
"width: 217px;\n"
"height: 15px;\n"
"left: 1070.6px;\n"
"top: 862.3px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"border: 1px solid rgba(255, 255, 255, 0.5);\n"
"border-radius: 3px;\n"
"color: #FFFFFF;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_30 = QtWidgets.QLabel(self.a)
        self.label_30.setStyleSheet("position: absolute;\n"
"width: 88px;\n"
"height: 15px;\n"
"left: 1065.04px;\n"
"top: 830.45px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;")
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.comboBox_2 = QtWidgets.QComboBox(self.a)
        self.comboBox_2.setMaximumSize(QtCore.QSize(217, 16777215))
        self.comboBox_2.setStyleSheet("background: rgba(85, 89, 93, 0.5);\n"
"position: absolute;\n"
"width: 217px;\n"
"height: 15px;\n"
"left: 1070.6px;\n"
"top: 862.3px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 12px;\n"
"line-height: 15px;\n"
"/* identical to box height */\n"
"\n"
"border: 1px solid rgba(255, 255, 255, 0.5);\n"
"border-radius: 3px;\n"
"color: #FFFFFF;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.label_43 = QtWidgets.QLabel(self.a)
        self.label_43.setMaximumSize(QtCore.QSize(20, 18))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("res/icon/bin.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_17.addWidget(self.label_43)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5.addWidget(self.a)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.label_2.setText(_translate("Main", "TextLabel"))
        self.label_8.setText(_translate("Main", "TextLabel"))
        self.pushButton_2.setText(_translate("Main", "PushButton"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Thời gian"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Loại cảnh báo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Thiết bị cảnh báo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Main", "Độ ưu tiên"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Main", "Trạng thái xử lí"))
        self.label_25.setText(_translate("Main", "Chi tiết báo động"))
        self.label_38.setText(_translate("Main", "Thời gian:"))
        self.label_37.setText(_translate("Main", "02/12/2022 10:03:12"))
        self.label_41.setText(_translate("Main", "Thiết bị cảnh báo:"))
        self.label_39.setText(_translate("Main", "Camera văn phòng"))
        self.label_42.setText(_translate("Main", "Loại cảnh báo:"))
        self.label_40.setText(_translate("Main", "Phát hiện di chuyển"))
        self.label_28.setText(_translate("Main", "Xử lí"))
        self.label_31.setText(_translate("Main", "Trạng thái xử lí"))
        self.comboBox_3.setItemText(0, _translate("Main", "Chưa xử lí           "))
        self.label_30.setText(_translate("Main", "Độ ưu tiên"))
        self.comboBox_2.setItemText(0, _translate("Main", "Bình thường"))
import res.resource_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
